// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsSzuOu4FFx01Cd-Jf-Ts08NQ2s3UATMQ',
    appId: '1:1011689133330:web:85585b9389edf425e14fcb',
    messagingSenderId: '1011689133330',
    projectId: 'todaytaskapp-b192d',
    authDomain: 'todaytaskapp-b192d.firebaseapp.com',
    storageBucket: 'todaytaskapp-b192d.firebasestorage.app',
    measurementId: 'G-1V7K25N5DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVeW2yOCFTQgIhRxlHXP9oNdbTOONw2G8',
    appId: '1:1011689133330:android:abfe48b1f56ce6d8e14fcb',
    messagingSenderId: '1011689133330',
    projectId: 'todaytaskapp-b192d',
    storageBucket: 'todaytaskapp-b192d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFUgLhO0y1Z8GfqcGG3zK0gk2mjaYlr6s',
    appId: '1:1011689133330:ios:b0ff00a3134976bbe14fcb',
    messagingSenderId: '1011689133330',
    projectId: 'todaytaskapp-b192d',
    storageBucket: 'todaytaskapp-b192d.firebasestorage.app',
    iosBundleId: 'com.example.todayTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFUgLhO0y1Z8GfqcGG3zK0gk2mjaYlr6s',
    appId: '1:1011689133330:ios:b0ff00a3134976bbe14fcb',
    messagingSenderId: '1011689133330',
    projectId: 'todaytaskapp-b192d',
    storageBucket: 'todaytaskapp-b192d.firebasestorage.app',
    iosBundleId: 'com.example.todayTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsSzuOu4FFx01Cd-Jf-Ts08NQ2s3UATMQ',
    appId: '1:1011689133330:web:9166963a6e3d6857e14fcb',
    messagingSenderId: '1011689133330',
    projectId: 'todaytaskapp-b192d',
    authDomain: 'todaytaskapp-b192d.firebaseapp.com',
    storageBucket: 'todaytaskapp-b192d.firebasestorage.app',
    measurementId: 'G-NWPM4B0FWM',
  );

}